package com.google.android.gms.internal;

import android.support.annotation.NonNull;
import com.google.android.gms.common.api.OptionalPendingResult;
import com.google.android.gms.common.api.PendingResult;
import com.google.android.gms.common.api.PendingResult.zza;
import com.google.android.gms.common.api.Result;
import com.google.android.gms.common.api.ResultCallback;
import com.google.android.gms.common.api.ResultTransform;
import com.google.android.gms.common.api.TransformedResult;
import java.util.concurrent.TimeUnit;

public final class zzqv<R extends Result>
  extends OptionalPendingResult<R>
{
  private final zzpt<R> vi;
  
  public zzqv(PendingResult<R> paramPendingResult)
  {
    if (!(paramPendingResult instanceof zzpt)) {
      throw new IllegalArgumentException("OptionalPendingResult can only wrap PendingResults generated by an API call.");
    }
    vi = ((zzpt)paramPendingResult);
  }
  
  public R await()
  {
    return vi.await();
  }
  
  public R await(long paramLong, TimeUnit paramTimeUnit)
  {
    return vi.await(paramLong, paramTimeUnit);
  }
  
  public void cancel()
  {
    vi.cancel();
  }
  
  public R get()
  {
    if (isDone()) {
      return await(0L, TimeUnit.MILLISECONDS);
    }
    throw new IllegalStateException("Result is not available. Check that isDone() returns true before calling get().");
  }
  
  public boolean isCanceled()
  {
    return vi.isCanceled();
  }
  
  public boolean isDone()
  {
    return vi.isReady();
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback)
  {
    vi.setResultCallback(paramResultCallback);
  }
  
  public void setResultCallback(ResultCallback<? super R> paramResultCallback, long paramLong, TimeUnit paramTimeUnit)
  {
    vi.setResultCallback(paramResultCallback, paramLong, paramTimeUnit);
  }
  
  @NonNull
  public <S extends Result> TransformedResult<S> then(@NonNull ResultTransform<? super R, ? extends S> paramResultTransform)
  {
    return vi.then(paramResultTransform);
  }
  
  public void zza(PendingResult.zza paramzza)
  {
    vi.zza(paramzza);
  }
  
  public Integer zzaog()
  {
    return vi.zzaog();
  }
}

/* Location:
 * Qualified Name:     com.google.android.gms.internal.zzqv
 * Java Class Version: 6 (50.0)
 * JD-Core Version:    0.7.1
 */